/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PalindromeMigratorInterface extends ethers.utils.Interface {
  functions: {
    "chef()": FunctionFragment;
    "desiredLiquidity()": FunctionFragment;
    "factory()": FunctionFragment;
    "migrate(address)": FunctionFragment;
    "notBeforeBlock()": FunctionFragment;
    "oldFactory()": FunctionFragment;
    "setFactoryProperties(uint256,address,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "chef", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "desiredLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "migrate", values: [string]): string;
  encodeFunctionData(
    functionFragment: "notBeforeBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oldFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFactoryProperties",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "chef", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "desiredLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "notBeforeBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oldFactory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFactoryProperties",
    data: BytesLike
  ): Result;

  events: {};
}

export class PalindromeMigrator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PalindromeMigratorInterface;

  functions: {
    chef(overrides?: CallOverrides): Promise<[string]>;

    desiredLiquidity(overrides?: CallOverrides): Promise<[BigNumber]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    migrate(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    notBeforeBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    oldFactory(overrides?: CallOverrides): Promise<[string]>;

    setFactoryProperties(
      _notBeforeBlock: BigNumberish,
      _oldFactory: string,
      _factory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  chef(overrides?: CallOverrides): Promise<string>;

  desiredLiquidity(overrides?: CallOverrides): Promise<BigNumber>;

  factory(overrides?: CallOverrides): Promise<string>;

  migrate(
    orig: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  notBeforeBlock(overrides?: CallOverrides): Promise<BigNumber>;

  oldFactory(overrides?: CallOverrides): Promise<string>;

  setFactoryProperties(
    _notBeforeBlock: BigNumberish,
    _oldFactory: string,
    _factory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    chef(overrides?: CallOverrides): Promise<string>;

    desiredLiquidity(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<string>;

    migrate(orig: string, overrides?: CallOverrides): Promise<string>;

    notBeforeBlock(overrides?: CallOverrides): Promise<BigNumber>;

    oldFactory(overrides?: CallOverrides): Promise<string>;

    setFactoryProperties(
      _notBeforeBlock: BigNumberish,
      _oldFactory: string,
      _factory: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    chef(overrides?: CallOverrides): Promise<BigNumber>;

    desiredLiquidity(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    migrate(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    notBeforeBlock(overrides?: CallOverrides): Promise<BigNumber>;

    oldFactory(overrides?: CallOverrides): Promise<BigNumber>;

    setFactoryProperties(
      _notBeforeBlock: BigNumberish,
      _oldFactory: string,
      _factory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    chef(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    desiredLiquidity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    migrate(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    notBeforeBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oldFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setFactoryProperties(
      _notBeforeBlock: BigNumberish,
      _oldFactory: string,
      _factory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
